blank_issues_enabled: false
contact_links:
  - name: Questions & Help
    url: https://github.com/Alexli18/memory-bank/discussions
    about: Ask questions and get help from the community in GitHub Discussions.
